### PR TITLE
Add travis-ci automated testing configuration

### PR DESCRIPTION
**Pull request by delgadom**
Hello again @GClunies!

I've found your package super useful and have recommended it to a couple collaborators! Figured a good place to start is with automated testing. I've added a working travis.yml file, which will tell [travis-ci.org](https://travis-ci.org) how to run tests on this package. You can check out the testing setup for my fork at https://www.travis-ci.org/delgadom/py_noaa/. All you'd need to do to add testing is to register with Travis (free) and add your repo (also free, because py_noaa is open source). Then, Travis will automatically test all pull requests, so you can tell with a glance whether the pull request will break your code.

If you're interested in this, feel free to ask for tips if you get stuck! If not, no worries :)

### CODE REVIEW

**Comment by GClunies** [comment]
Hey @delgadom! I'm glad you have found the package useful, I wasn't sure it would ever be used apart from myself. I started it mainly as an exercise for my continued learning of python and to see how a package is put together. It's definitely rough right now as I've encountered some cases where I hit errors. But it seems to work reasonably well for the example cases in the README.

I am very glad to have any help you can offer. Automated testing is entirely foreign to me, but my basic understanding is that it's put place to protect your code from being broken by an error that may be submitted as part of a pull request. Correct?

I'll register this repo with Travis-CI and we can go from there. I suppose my only request is that you bear with me as I am sure to ask a lot of questions along the way!

**Comment by GClunies** [comment]
@delgadom, couple of questions about the files for setting up Travis-CI intergration

`.gitignore` - changes makes sense
`.travis.yml` - understand on a high level. This file is used fro setup of travis integration
`README.md` - Why do arguments in the README examples have to be listed vertically?
`pytest.ini` - what is line 3 accomplishing? shown below?
```
addopts = --cov=py_noaa --cov=tests --doctest-modules --cov-report term-missing --doctest-glob='*.md'
```
`requirements.txt` - changes makes sense
`tests/test_py_noaa.py` - why do you test with a case that you know will not work (invalid datum)?

`py_noaa/coops.py` -  Thanks for this additional fix

Would be great if you could briefly fill me in so I can have some  understanding instead of just blindly merging. Thanks again for the tips!

**Comment by delgadom** [comment]
@GClunies thanks for being willing to give this all a try! Let me know if you want me to back off, and I'll just fork the repo :)

Also, apologies - I should have separated these into a few different PRs. Here's my logic behind these changes:

* .gitignore - just added files generated by testing suite
* .travis.yml - yep! it's a yaml file with a set of structured bash-style instructions to be run on the travis servers
* README.md - they don't have to be, but then they don't go off the page to the right. a little easier to read, and in line with [python style guidelines](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). I also fixed a couple things - the current readme didn't pass tests so that's why I started modifying it.
* pytest.ini - this sets the default options for testing, so that you can just run `pytest` instead of using all these options. It's not necessary - these options could be included in travis.yml instead of here if you'd rather not include this file.
* requirements.txt - yeah these are the additional requirements for development/testing
* tests/test_py_noaa.py - this was just a placeholder to demonstrate additional testing options. in this case, I make sure that an invalid option will raise a ValueError, rather than a KeyError or some other unexpected error as was previously the case. So it's actually asserting that errors sent by NOAA are properly handled.
* py_noaa/coops.py - this is just a py27 fix - up to you whether you want to support

If you'd prefer, I can delete this PR and seperate these. It was a bit easier to combine a couple changes into one, because once I added tests I found a couple things that failed them.

Thanks!

**Comment by GClunies** [comment]
Thanks for the explanation @delgadom. I feel like this is a great learning opportunity for me so I am happy to have your help. 

I agree with keeping it as one PR since it's genera;;y all associated with implementing testing. I can't say my commit structure has been stellar so far so I pass no judgement! 😆

**Pull request merged**
