### PR TITLE
Add support for hilo prediction interval & remove whitespace.

### PR DESCRIPTION
**Pull request by jcconnell**
I'm planning to use this library for a Home Assistant sensor.  I noticed that the hilo interval was not supported so I made a change. I also removed some whitespace. I plan to make another PR to add support for the range URL parameter.

### CODE REVIEW

**Comment by GClunies** [comment]
@jcconnell, thanks for the PR! 

Just a few things:
- Thanks for cleaning up the whitespace!
- Any chance you can update the **`README.md`** with an example use case? Similar to what I have done for other examples. It would be great for end users to see this functionality in the documentation and not have to stumble upon it themselves!

**Comment by jcconnell** [comment]
@GClunies No problem! I've just updated the `README.md` to include another example. I'll eventually add the range parameter as well.

**Comment by jcconnell** [comment]
@GClunies These most recent changes add support for all four of the supported CO-OPS date formats as input. I have also modified the URL building function and the response JSON parsing to use Python Requests library since it was already imported. The Requests URL builder supports escaping spaces in URL parameters, such as the now supported datetime formats like `yyyyMMdd HH:mm`. 

I have also modified the Home Assistant NOAA_Tides sensor[here](https://github.com/home-assistant/home-assistant/pull/15664) in preparation for these changes. If you find these changes acceptable, would you consider accepting the PR and publishing the update to PyPi so I can push the updates to that PR also? I'm happy to make any changes to the README also.

**Comment by GClunies** [comment]
@jcconnell, this looks great! Will Merge your PR now.

I have another PR (#22) ... adding functionality for high/low **observations** (your PR handles the prediction side of things), which just needs a minor tweak before I merge it as well. 

Once I have both PRs merged it will be a good time to update to PyPi. Thanks for your patience.

**Comment by GClunies** [comment]
Will also add you as contributor @jcconnell !

**Comment by jcconnell** [comment]
Thank you @GClunies!

**Pull request merged**
